# Generated by Django 3.1.4 on 2020-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='import_bulk',
            field=models.CharField(null=True, blank=True, max_length=100)
        ),
        migrations.AddField(
            model_name='user',
            name='extra',
            field=models.CharField(null=True, blank=True, max_length=300, default='')
        )
    ]
