# Generated by Django 3.1.4 on 2021-01-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_auto_20201223_1031'),
        ('citizens', '0003_bulk_import_and_extra'),
    ]

    operations = [
    ]
